# Generated by Django 3.0.5 on 2020-06-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='statistic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Statistic'),
        ),
    ]
