# Generated by Django 3.0.5 on 2020-06-30 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200630_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='statistic',
        ),
        migrations.AddField(
            model_name='statistic',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
