# Generated by Django 3.0.5 on 2020-06-30 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200630_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='was_answered',
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
