# Generated by Django 3.0.5 on 2020-07-01 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200701_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='answered',
        ),
        migrations.AddField(
            model_name='answered',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
