# Generated by Django 3.0.5 on 2020-07-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200701_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answered',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='answered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='question.Answered'),
        ),
    ]
