# Generated by Django 3.0.5 on 2020-07-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20200701_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
